name: Restrict PRs and Deploy

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  restrict-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      - name: Check source branch

        if: github.event.pull_request.head.ref != 'dev'
        run: exit 1

  deploy:
    # if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      - name: Deploy to Vercel

        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
